spring.application.name=finance_tracker
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_tracker
spring.datasource.username=postgres
spring.datasource.password=260399

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
